### ISSUE TITLE
新手请教

### ISSUE THREAD

**Issue by JiangLingJun** [wstart/wechat_AlphaJump#1]
请问前辈,环境已搭建程序能运行.但是运行程序时第一步那个小人就以最远距离弹射,而且record文件夹中自动添加几张图片后程序就崩了...提示数组越界...

**Comment by ghost** [comment]
他的代码有个小问题，我不理解为什么要旋转90度，你把那一句删了应该就可以了 @JiangLingJun j

**Comment by wstart** [comment]
> 他的代码有个小问题，我不理解为什么要旋转90度，你把那一句删了应该就可以了 @JiangLingJun j

别说了 。。国产手机傻逼。。。截图出来是横着的。。
我也是多年以后才发现
